In [9]:
import math
from pprint import pprint
from math import log
import numpy as np
import sys
from typing import List, Tuple, Callable, Iterable
from functools import lru_cache, reduce, cmp_to_key
from itertools import (
    starmap,
    accumulate,
    chain,
    islice,
    product,
    tee,
    pairwise,
    combinations,
)
from collections import Counter, deque
from heapq import heapify, heappushpop, heappop, heappush
from operator import add, neg, itemgetter
from bisect import bisect_right
import matplotlib.pyplot as plt

import arrays
import trees
import lists
import graphs
import search
import strings
from importlib import reload

reload(arrays)
reload(trees)
reload(lists)
reload(graphs)
reload(search)
import arrays as ar
import trees as tr
import lists as ll
import graphs as g
import strings as s

print()

In [72]:
def max_zero_sum_subarray(a: List[int]) -> int:
    n = len(a)
    acc = list(accumulate(a, initial=0))
    occ = dict((a, n - i) for i, a in enumerate(reversed(acc)))
    return max(starmap(lambda i, e: i - occ[e], enumerate(acc)))

In [80]:
def max_zero_sum_subarray(a: List[int]) -> int:
    occ = {0: -1}
    for i, e in enumerate(accumulate(a)):
        occ.setdefault(e, i)
    return max(starmap(lambda i, e: i - occ[e], enumerate(accumulate(a))))

In [83]:
max_zero_sum_subarray([15, -2, 2, -8, 1, 7, 10, 23])

5

In [183]:
def max_sum_rectangle(m: List[List[int]]) -> int:
    r, c = len(m), len(m[0])
    mx = min(map(min, m))
    for i in range(c):
        a = [0] * r
        for j in range(i, c):
            for k in range(r):
                a[k] += m[k][j]
            mx = max(mx, max(accumulate(a, lambda x, y: max(0, x + y), initial=0)))
    return mx if mx > 0 else max(map(max, m))

In [210]:
def max_sum_rectangle(m: List[List[int]]) -> int:
    r, c = len(m), len(m[0])
    mx = min(map(min, m))
    for i in range(r):
        a = [0] * c
        for j in range(i, r):
            mj = m[j]
            for k in range(c):
                a[k] += mj[k]
            mx = max(mx, max(accumulate(a, lambda x, y: max(0, x + y), initial=0)))
    return mx if mx > 0 else max(map(max, m))

In [206]:
def max_sum_rectangle(m: List[List[int]]) -> int:
    m = np.array(m)
    r, c = m.shape
    a = np.add.accumulate(m)
    k = lambda a: max(accumulate(a, lambda x, y: max(0, x + y), initial=0))
    mx = max(k(a[i]) for i in range(r))
    for i, j in combinations(range(r), 2):
        mx = max(mx, k(a[j] - a[i]))
    return mx if mx > 0 else np.max(m)

In [211]:
max_sum_rectangle(
    [[9, -9, 1, -4, -1, 9, -10], [3, -3, -4, -2, -5, 3, -6], [-7, 2, -5, 1, -10, 4, -4]]
)

16

In [207]:
max_sum_rectangle([[-1, -2], [-3, -4]])

-1

In [208]:
max_sum_rectangle(
    [[1, 2, -1, -4, -20], [-8, -3, 4, 2, 1], [3, 8, 10, 1, 3], [-4, -1, 1, 7, -6]]
)

29

In [162]:
list(combinations(range(3), 2))

[(0, 1), (0, 2), (1, 2)]

In [209]:
m = np.array(
    [[1, 2, -1, -4, -20], [-8, -3, 4, 2, 1], [3, 8, 10, 1, 3], [-4, -1, 1, 7, -6]]
)
print(np.min(m))
ac = np.add.accumulate(m, 1)

-20


In [147]:
ac[0] - ac[1]

array([  9,  14,   9,   3, -18])

In [149]:
list(accumulate(m))

[array([  1,   2,  -1,  -4, -20]),
 array([ -7,  -1,   3,  -2, -19]),
 array([ -4,   7,  13,  -1, -16]),
 array([ -8,   6,  14,   6, -22])]